# Generated by Django 3.2 on 2021-06-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='code',
        ),
    ]
